### ISSUE TITLE
Can I set env-var in the workflow file

### ISSUE THREAD

**Issue by AboulEinein** [matt-ball/newman-action#4]
I have env variables that contain username and password that are not committed to the environment or global files, is it possible to set them in the workflow file and use GitHub secrets?

**Comment by hunterlong** [comment]
+1 on this question.

**Comment by matt-ball** [comment]
Yes, see the README:
https://github.com/matt-ball/newman-action#example-workflow-file

In that example, the Postman API key is being retrieved from a GitHub secret, but you could use a secret in place of any value. I've previously used GitHub secrets to hold some JSON configuration which gets piped in in exactly the same way.

**Comment by AboulEinein** [comment]
@matt-ball thanks for the reply, but my question is how to set multiple env variables? It would be great if you provide an example.

**Comment by matt-ball** [comment]
The [Action uses Newman's API](https://github.com/matt-ball/newman-action#other-settings) under the hood, so that's the format you'll need to be using:
https://github.com/postmanlabs/newman#api-reference

So, for environment you can provide a string or an object. If you want to use multiple environment variables, you need to go the object route. [Exporting an environment](https://learning.postman.com/docs/postman/collections/importing-and-exporting-data/#exporting-environments) from Postman with these values will build the JSON for you, but the most stripped down version looks like:

```
{
  "values": [
    {
      "key": "url",
      "value": "https://example.com"
    }
  ]
}
```

Adding more objects to the values array will give you more environment variables. Place the resulting object in a GitHub secret and reference in your Action file as described above.

**Comment by gandhish** [comment]
Any pointers on specifying multiple environment variables from github secrets. Dont want to use --env-var, but an environment variables file that can reference from github secrets.
